// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcZoRjW66eTknFoyXawzNZ0hvVI39ezQ0',
    appId: '1:142092570852:android:4353a4257de55222475cf1',
    messagingSenderId: '142092570852',
    projectId: 'the-original-lab-ca4be',
    storageBucket: 'the-original-lab-ca4be.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqU6VrXxp2pzQelqVNuXc5GZHYiL-BVxs',
    appId: '1:142092570852:web:1bad3fb5098cb0b8475cf1',
    messagingSenderId: '142092570852',
    projectId: 'the-original-lab-ca4be',
    authDomain: 'the-original-lab-ca4be.firebaseapp.com',
    storageBucket: 'the-original-lab-ca4be.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZw-FFhMhct7vuVTCWPDx-rlVzykq3ybM',
    appId: '1:142092570852:ios:8568dbbd3172baf5475cf1',
    messagingSenderId: '142092570852',
    projectId: 'the-original-lab-ca4be',
    storageBucket: 'the-original-lab-ca4be.firebasestorage.app',
    iosBundleId: 'com.theoriginallab.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZw-FFhMhct7vuVTCWPDx-rlVzykq3ybM',
    appId: '1:142092570852:ios:8568dbbd3172baf5475cf1',
    messagingSenderId: '142092570852',
    projectId: 'the-original-lab-ca4be',
    storageBucket: 'the-original-lab-ca4be.firebasestorage.app',
    iosBundleId: 'com.theoriginallab.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqU6VrXxp2pzQelqVNuXc5GZHYiL-BVxs',
    appId: '1:142092570852:web:1f437d7599f1a50f475cf1',
    messagingSenderId: '142092570852',
    projectId: 'the-original-lab-ca4be',
    authDomain: 'the-original-lab-ca4be.firebaseapp.com',
    storageBucket: 'the-original-lab-ca4be.firebasestorage.app',
  );
}
